version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.7.14
    steps:
      - checkout
      - run: python --version
      - run: make setup
      - run: make install
      - run: make lint
      - run: make test
      - run: docker --help


workflows:
  default:
    jobs:
      - build