version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.7.14
    steps:
      - checkout
      - run: python --version
      - run: pip install --no-cache-dir --upgrade pip==22.3
      - run: pip install --no-cache-dir -r requirements.txt
      - run: make lint
      - run: make test
      - run: docker --help


workflows:
  default:
    jobs:
      - build