version: 2.1

orbs:
  docker: circleci/docker@2.1.4


jobs:
  lint:
    docker:
      - image: cimg/python:3.7.14
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run: python3 -m venv ~/.devops
      - run: source ~/.devops/bin/activate
      - run: pip install --no-cache-dir --upgrade pip==22.3
      - run: pip install --no-cache-dir -r requirements.txt
      - run: docker run --rm -i hadolint/hadolint < Dockerfile
      - run: pylint --disable=R,C,W1203,W1202 app.py

  test:
    docker:
      - image: cimg/python:3.7.14
    steps:
      - checkout
      - run: python3 -m venv ~/.devops
      - run: source ~/.devops/bin/activate
      - run: pip install --no-cache-dir --upgrade pip==22.3
      - run: pip install --no-cache-dir -r requirements.txt
      - run: make test
      - run: docker --help

  build:
    docker:
      - image: cimg/python:3.7.14
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run: docker build -t braxnu/uda-kube .
      - run: docker login -u braxnu -p '$DOCKERHUB_PASSWORD'
      - run: docker push braxnu/uda-kube:latest


workflows:
  default:
    jobs:
      - lint
      - test:
          requires:
            - lint
      - build:
          requires:
            - lint
